# Generated by Django 4.2.23 on 2025-06-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(default='fed50a6f82f34aae90a5', max_length=20, unique=True),
        ),
    ]
