# Generated by Django 4.2.23 on 2025-06-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_bankaccount_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(default='80e058feb75540eca47e', max_length=20, unique=True),
        ),
    ]
