# Generated by Django 4.2.23 on 2025-06-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_card_balance_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(default='6a29608af4804b8ca887', max_length=20, unique=True),
        ),
    ]
