# Generated by Django 4.2.23 on 2025-06-16 08:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_bankaccount_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='status',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(default='748b1d53171245fca33c', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))]),
        ),
    ]
