# Generated by Django 4.2.23 on 2025-06-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_transfer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(default='08efeca366a9436fb189', max_length=20, unique=True),
        ),
    ]
